# Generated by Django 4.2.11 on 2026-02-07 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ampayer_1',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ampayer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_ampayer_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='ampayer_2',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ampayer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_ampayer_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='ampayer_3',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ampayer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_ampayer_3', to=settings.AUTH_USER_MODEL),
        ),
    ]
