# Generated by Django 4.2.11 on 2026-02-07 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_game_ampayer_1_game_ampayer_2_game_ampayer_3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='play',
            options={'ordering': ['game', 'inning', 'created_at']},
        ),
        migrations.RenameField(
            model_name='play',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='play',
            old_name='half_inning',
            new_name='half',
        ),
        migrations.RemoveField(
            model_name='play',
            name='outs_recorded',
        ),
        migrations.RemoveField(
            model_name='play',
            name='rbi',
        ),
        migrations.RemoveField(
            model_name='play',
            name='result',
        ),
        migrations.AddField(
            model_name='game',
            name='away_errors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='away_hits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='game_highlights',
            field=models.TextField(blank=True, help_text='Lo más sobresaliente del juego', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='general_comments',
            field=models.TextField(blank=True, help_text='Comentarios generales', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_errors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='home_hits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='losing_pitcher',
            field=models.ForeignKey(blank=True, help_text='Pitcher perdedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_lost', to='core.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='modality',
            field=models.CharField(blank=True, help_text='Modalidad del juego', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='service_rating',
            field=models.CharField(blank=True, choices=[('malo', 'Malo'), ('regular', 'Regular'), ('bueno', 'Bueno')], help_text='Calificación del servicio', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='sponsor',
            field=models.CharField(blank=True, help_text='Patrocinador del juego', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='winning_pitcher',
            field=models.ForeignKey(blank=True, help_text='Pitcher ganador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won', to='core.player'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='AB',
            field=models.PositiveIntegerField(default=0, help_text='Turnos al bat'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='BB',
            field=models.PositiveIntegerField(default=0, help_text='Base por bolas'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='CS',
            field=models.PositiveIntegerField(default=0, help_text='Atrapado robando'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='H',
            field=models.PositiveIntegerField(default=0, help_text='Hits'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='HBP',
            field=models.PositiveIntegerField(default=0, help_text='Golpeado por lanzamiento'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='HR',
            field=models.PositiveIntegerField(default=0, help_text='Home Runs'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='IBB',
            field=models.PositiveIntegerField(default=0, help_text='Base por bolas intencional'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='LOB',
            field=models.PositiveIntegerField(default=0, help_text='Corredores dejados en base'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='PA',
            field=models.PositiveIntegerField(default=0, help_text='Apariciones al plato'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='R',
            field=models.PositiveIntegerField(default=0, help_text='Carreras anotadas'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='RBI',
            field=models.PositiveIntegerField(default=0, help_text='Carreras impulsadas'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='SB',
            field=models.PositiveIntegerField(default=0, help_text='Base robada'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='SF',
            field=models.PositiveIntegerField(default=0, help_text='Elevado de sacrificio'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='SH',
            field=models.PositiveIntegerField(default=0, help_text='Toque de sacrificio'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='SO',
            field=models.PositiveIntegerField(default=0, help_text='Ponches'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='TB',
            field=models.PositiveIntegerField(default=0, help_text='Total de bases'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='doubles',
            field=models.PositiveIntegerField(default=0, help_text='Dobles (2B)'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='singles',
            field=models.PositiveIntegerField(default=0, help_text='Sencillos (1B)'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='triples',
            field=models.PositiveIntegerField(default=0, help_text='Triples (3B)'),
        ),
        migrations.AddField(
            model_name='play',
            name='event_type',
            field=models.CharField(default='Unknown', help_text='Single, Double, Out, etc.', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='play',
            name='batter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays_as_batter', to='core.player'),
        ),
        migrations.AlterField(
            model_name='play',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='pitcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays_as_pitcher', to='core.player'),
        ),
        migrations.CreateModel(
            name='PitchingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.DecimalField(decimal_places=1, default=0.0, help_text='Entradas lanzadas', max_digits=4)),
                ('BF', models.PositiveIntegerField(default=0, help_text='Bateadores enfrentados')),
                ('H', models.PositiveIntegerField(default=0, help_text='Hits permitidos')),
                ('R', models.PositiveIntegerField(default=0, help_text='Carreras')),
                ('ER', models.PositiveIntegerField(default=0, help_text='Carreras limpias')),
                ('BB', models.PositiveIntegerField(default=0, help_text='Bases por bolas')),
                ('SO', models.PositiveIntegerField(default=0, help_text='Ponches')),
                ('is_winner', models.BooleanField(default=False, help_text='Pitcher ganador')),
                ('is_loser', models.BooleanField(default=False, help_text='Pitcher perdedor')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitching_stats', to='core.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitching_performances', to='core.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'verbose_name_plural': 'Pitching Stats',
                'unique_together': {('game', 'player')},
            },
        ),
    ]
