# Generated by Django 4.2.11 on 2026-02-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_stadium_capacity_stadium_field_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('game_assignment', 'Asignación de Juego'), ('game_reminder', 'Recordatorio de Juego'), ('game_cancellation', 'Cancelación de Juego'), ('score_request', 'Solicitud de Anotación'), ('general_info', 'Información General')], default='general_info', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
    ]
