# Generated by Django 4.2.11 on 2026-02-07 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification_accepted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='scorer',
        ),
        migrations.AddField(
            model_name='game',
            name='scorer_1',
            field=models.ForeignKey(blank=True, help_text='Anotador Oficial', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scored_games_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='scorer_2',
            field=models.ForeignKey(blank=True, help_text='Anotador Auxiliar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scored_games_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
