# Generated by Django 4.2.11 on 2026-02-11 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_game_scorer_game_scorer_1_game_scorer_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Motivo de la cancelación', null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='error_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors_committed', to='core.player'),
        ),
        migrations.AddField(
            model_name='play',
            name='fielders_involved',
            field=models.CharField(blank=True, help_text="Posiciones involucradas (e.g., '6-3', 'F8')", max_length=50),
        ),
        migrations.AddField(
            model_name='play',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='play',
            name='is_hit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='play',
            name='outs_recorded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='play',
            name='runner_on_1st_moved_to',
            field=models.PositiveIntegerField(blank=True, help_text='Base 2, 3, or 4 (Home)', null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='runner_on_2nd_moved_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='runner_on_3rd_moved_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UmpireReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Detalles del reporte (incidentes, estado del campo, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umpire_reports', to='core.game')),
                ('umpire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
