# Generated by Django 4.2.11 on 2026-02-12 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_game_cancellation_reason_play_error_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='incoming_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_in', to='core.player'),
        ),
        migrations.AddField(
            model_name='play',
            name='is_fielders_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='play',
            name='is_sacrifice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='play',
            name='is_substitution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='play',
            name='outgoing_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_out', to='core.player'),
        ),
        migrations.AddField(
            model_name='play',
            name='position_change',
            field=models.CharField(blank=True, help_text="e.g. 'P' or '1B'", max_length=50, null=True),
        ),
    ]
