# Generated by Django 4.2.11 on 2026-02-12 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_game_actual_end_time_game_actual_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='outs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='runner_on_1b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_on_1b', to='core.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='runner_on_2b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_on_2b', to='core.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='runner_on_3b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_on_3b', to='core.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='strikes',
            field=models.IntegerField(default=0),
        ),
    ]
