# Generated by Django 4.2.11 on 2026-02-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_game_balls_game_outs_game_runner_on_1b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_inning',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='inning_half',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], default='top', max_length=10),
        ),
    ]
