# Generated by Django 4.2.11 on 2026-03-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_game_current_inning_game_inning_half'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineupentry',
            options={'ordering': ['game', 'team', 'batting_order', 'entry_inning']},
        ),
        migrations.AlterUniqueTogether(
            name='lineupentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='entry_inning',
            field=models.PositiveIntegerField(default=1, help_text='Entrada en la que entró'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='exit_inning',
            field=models.PositiveIntegerField(blank=True, help_text='Entrada en la que salió', null=True),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='is_active',
            field=models.BooleanField(default=True, help_text='¿Sigue en el juego?'),
        ),
    ]
