# Generated by Django 4.2.11 on 2026-05-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_lineupentry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='positions',
            field=models.CharField(blank=True, default='', help_text="Comma-separated positions (e.g., 'P, SS')", max_length=100),
        ),
    ]
