# Generated by Django 4.2.11 on 2026-05-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_player_optional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineupentry',
            name='IP_outs',
            field=models.PositiveIntegerField(default=0, help_text='Outs conseguidos como pitcher (3 = 1 entrada)'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='pitch_BB',
            field=models.PositiveIntegerField(default=0, help_text='Bases por bolas otorgadas'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='pitch_ER',
            field=models.PositiveIntegerField(default=0, help_text='Carreras limpias permitidas'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='pitch_H',
            field=models.PositiveIntegerField(default=0, help_text='Hits permitidos'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='pitch_HR',
            field=models.PositiveIntegerField(default=0, help_text='Home runs permitidos'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='pitch_R',
            field=models.PositiveIntegerField(default=0, help_text='Carreras permitidas'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='pitch_SO',
            field=models.PositiveIntegerField(default=0, help_text='Ponches recetados'),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='pitch_loss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='pitch_save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lineupentry',
            name='pitch_win',
            field=models.BooleanField(default=False),
        ),
    ]
