# Generated by Django 4.2.11 on 2026-05-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_lineupentry_ip_outs_lineupentry_pitch_bb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='jersey_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
